### ISSUE TITLE
install hylar@1.10.2 failed

### ISSUE THREAD

**Issue by crapthings** [ucbl/HyLAR-Reasoner#16]
```
npm install --save hylar
npm ERR! code 128
npm ERR! Command failed: git clone --mirror -q https://github.com/mterdjimi/rdfstore-js.git /Users/monsterstep/.npm/_cacache/tmp/git-clone-94754f51/.git
npm ERR! warning: templates not found in /var/folders/g_/9zn58k_16m50w1z3tqvq65xr0000gn/T/pacote-git-template-tmp/git-clone-60c34e39
npm ERR! error: RPC failed; curl 18 transfer closed with outstanding read data remaining
npm ERR! fatal: the remote end hung up unexpectedly
npm ERR! fatal: early EOF
npm ERR! fatal: index-pack failed
npm ERR!

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/monsterstep/.npm/_logs/2020-05-15T05_30_07_762Z-debug.log
```

```
dev/owl-playground/hylar is 📦  v1.0.0 via ⬢ v14.2.0 took 1m 58s
👽 node -v
v14.2.0

dev/owl-playground/hylar is 📦  v1.0.0 via ⬢ v14.2.0
👽 npm -v
6.14.4
```

i've tried node 10 and 12

all failed

**Comment by mterdjimi** [comment]
New HyLAR versions use a forked version of rdfstore, to solve various issues related to SPARQL and package vulnerabilities. Hence, `npm install` will also perform a `git clone --mirror -q https://github.com/mterdjimi/rdfstore-js.git` as shown in your error log.

The `curl 18` error seems to be related to your internet connection. This may refer to a git buffer size limit as well (cf. https://github.com/CocoaPods/CocoaPods/issues/9564).

Consider using a older version of HyLAR ([1.9.1](https://github.com/ucbl/HyLAR-Reasoner/releases/tag/v1.9.1) for instance)

**Comment by crapthings** [comment]
okay will try thanks @mterdjimi
