### ISSUE TITLE
 Impossible to load a JSON-LD that contains the ```@language``` keyword

### ISSUE THREAD

**Issue by StatelessCat** [ucbl/HyLAR-Reasoner#3]
Hey,
It seems that it's impossible to load a JSON-LD that contains the @language keyword.
For example: ```'@language': 'en-us'``` causes an ```{ SyntaxError: Expected [1] QueryUnit or [29] UpdateUnit but "I" found.``` error.
```rdfstore/src/parser.js:2760:14``` Seems to be the cause.

Here you will find a minimal working example: https://github.com/StatelessCat/mwe-hylar/blob/292112453f04d6c32be93b5bc5887c3b9afb3917/mwe-hylar.js#L13 .

I'll check if I can reproduce the bug on `rdfstore` directly.

Thanks in advance for your help.
Raphaël .

**Comment by Spadon** [comment]
Hi,
Thanks for the report. The literal matching regexp was incorrect. This issue is now solved since 76053ce.

Best,
Mehdi
