### ISSUE TITLE
Cannot initialize Hylar in a browser

### ISSUE THREAD

**Issue by lorz** [ucbl/HyLAR-Reasoner#8]
Hi there, I've tried to use Hylar-reasoner in a stand-alone browse as follows:

index.html:
<script language="javascript" type="text/javascript" src="/resources/js/hylar/hylar-client.js"></script>

<script>
h = new Hylar();
</script>

But just get this error: ReferenceError: Hylar is not defined

What am I doing wrong? I'm not using node neither bower nor anything. Just a plain call to the JS file.

**Comment by Spadon** [comment]
Hi,

Are you using the hylar-client.js file from the current hylar npm package ?

**Comment by lorz** [comment]
Hello Mehdi, thank you for your answer. I'm using the hylar-client.js directly from my code. I mean, just a plain call to the library as: <script type="text/javascript" src="hylar-client.js"></script>


Do I need to use npm? I'm making a pure client javascript application, so I would like not to install anything in the server.


Could you tell me if is npm strictly needed?



Thank you! Regards!

________________________________
De: Mehdi Terdjimi <notifications@github.com>
Enviado: viernes, 2 de febrero de 2018 14:56
Para: ucbl/HyLAR-Reasoner
Cc: lorz; Author
Asunto: Re: [ucbl/HyLAR-Reasoner] Cannot initialize Hylar in a browser (#8)


Hi,

Are you using the hylar-client.js file from the current hylar npm package ?

**Comment by Spadon** [comment]
Yes, HyLAR can also be used in a client-only application (without any server). However, I was wondering which version of hylar-client you are using (either the one from the npm repository, the bower repo or the current github version).

Thanks

**Comment by lorz** [comment]
I've just tried the git hub version.


Thank you Mehdi. Keep in touch.


________________________________
De: Mehdi Terdjimi <notifications@github.com>
Enviado: viernes, 2 de febrero de 2018 23:59
Para: ucbl/HyLAR-Reasoner
Cc: lorz; Author
Asunto: Re: [ucbl/HyLAR-Reasoner] Cannot initialize Hylar in a browser (#8)


Yes, HyLAR can also be used in a client-only application (without any server). However, I was wondering which version of hylar-client you are using (either the one from the npm repository, the bower repo or the current github version).

Thanks

**Comment by lorz** [comment]
Dear Mehdi, I write you because today a friend of mine sent me the "hylar-client.js" file, downloaded via npm, and I could test it again in my browser.


Same as happened before, when I call the library: <script language="javascript" type="text/javascript" src="/fowl/resources/js/hylar/hylar-client.js"></script> the browser (Firefox Developer 57.0b3) throws the same exception:


ReferenceError: Hylar is not defined
[Learn More]



I still can't find out what's wrong with the code. By this time, maybe you could discover something...


Thank you!





________________________________
De: Mehdi Terdjimi <notifications@github.com>
Enviado: viernes, 2 de febrero de 2018 23:59
Para: ucbl/HyLAR-Reasoner
Cc: lorz; Author
Asunto: Re: [ucbl/HyLAR-Reasoner] Cannot initialize Hylar in a browser (#8)


Yes, HyLAR can also be used in a client-only application (without any server). However, I was wondering which version of hylar-client you are using (either the one from the npm repository, the bower repo or the current github version).

Thanks

**Comment by Spadon** [comment]
Could you please send me the files (including the hylar-client.js) so I can reproduce the error ?

Thanks in advance.
