### ISSUE TITLE
Console error messages overrided by HyLAR

### ISSUE THREAD

**Issue by alexislebis** [ucbl/HyLAR-Reasoner#9]
Hi !

I use HyLAR in a browser version, and it appears that HyLAR catch and then overrides the error messages thrown by my application such as :
`[HyLAR] ERROR : An error`

The incriminated function is located line 2646 in [hylar-client.js](https://github.com/ucbl/HyLAR-Reasoner/blob/master/hylar-client.js).
Is this behavior intentional? 

Regards

EDIT:
It also seems to be the case for warnings.

**Comment by Spadon** [comment]
Hi !

Thanks for raising this issue. Error and warning overriding is not intentional on the client side, and was originally used for the node.js (server-side) version only.

I fix this asap.

**Comment by mterdjimi** [comment]
Hi back,

The recent commit 65c900f must have corrected this issue. Could pull this commit and confirm if it works on your side, please?
Thanks!
